markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0

concurrency:
  group- Wait for the current deployment to finish before triggering: pages-deployment
  cancel-in-progress: true
