name: Build Jekyll Site

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fail if _config.yml is missing
        run: |
          if [ ! -f "_config.yaml" ]; then
            echo "❌ _config.yaml is missing. Jekyll requires this file."
            exit 1
          fi

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: |
          bundle exec jekyll build --trace
