name: Build Jekyll Site

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure _config.yml exists
        run: |
          if [ ! -f "_config.yml" ]; then
            if [ -f "_config.yaml" ]; then
              cp _config.yaml _config.yml
              echo "✅ Copied _config.yaml to _config.yml"
            else
              echo "❌ No _config.yml or _config.yaml found"
              exit 1
            fi
          fi

      - name: Install svgo
        run: npm install -g svgo

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Patch jekyll-minifier bug
        run: |
          sed -i '1s/^/module Jekyll; class StaticFile; @@mtimes ||= {}; end; end\n/' $(bundle show jekyll-minifier)/lib/jekyll-minifier.rb

      - name: Build site
        run: bundle exec jekyll build --trace
