name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Docker
        run: |
          docker run \
          --rm \
          --user $(id -u):$(id -g) \
          --volume="${{ github.workspace }}:/srv/jekyll" \
          --volume="${{ github.workspace }}/_site:/srv/jekyll/_site" \
          jekyll/builder:latest \
          /bin/bash -c "chmod 755 /srv/jekyll && jekyll build"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: pages-deployment
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
