name: Build Jekyll Site

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure _config.yml exists for plugins
        run: |
          if [ ! -f "_config.yml" ]; then
            if [ -f "_config.yaml" ]; then
              cp _config.yaml _config.yml
              echo "✅ Copied _config.yaml to _config.yml for Jekyll compatibility."
            else
              echo "❌ No _config.yml or _config.yaml found — cannot build."
              exit 1
            fi
          fi

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build --trace
